### ISSUE TITLE
Create new CV based on deprecated CV

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#103]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

The user deprecates a CV and then creates a new CV based on the deprecated CV content.

This is a rare case but has happened once for a DDI vocabulary \(at that time, the previous CV was deleted, there was no deprecation\). There a CV meant for a DDI element was determined to be better for another element. This required changing the CV name and short name, in addition to Usage information, but the actual code content did not change.

Can ADMIN in that rare case copy the SL and TL content from the deprecated CV, and what about the code-level identifiers?

If the CV is not long, it is probably easier to just copy paste the needed information.

See also #433.

Assigning to Maja so she can review the issue and its importance or lack or it at some point in 2023.

**Comment by MajaDolinar** [comment]
Closing for now since it is not important at this time - we do not have such cases yet in the system.
