### ISSUE TITLE
Exported csv files have encoding issues

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#219]
**Original report on BitBucket by Henri Ala-Lahti.**

----------------------------------------

When exporting a csv file of a CV, some special characters won’t display properly:

![](https://bitbucket.org/repo/A6bqkay/images/3311731106-csv%20export.png)
‌

Can this be fixed by the user? If yes, we need to update the User Guide.

**Comment by matthew-morris-cessda** [comment]
Excel relies on the presence of a [UTF-8 byte-order mark](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8) in order to parse CSVs as Unicode. Currently the exporter does not include this metadata.
