### ISSUE TITLE
Possibility to create an export of version comparison?

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#270]
**Original report on BitBucket by Henri Ala-Lahti.**

----------------------------------------

Users asked whether it would be possible to create a button that would export the version comparison into a file \(maybe csv? Or something else that would show the differences easily\). This would allow them to work with the comparison and their translations simultaneously.

![](https://bitbucket.org/repo/A6bqkay/images/3902257234-compareversion.PNG)
‌

**Comment by Lorenz1983** [comment]
When exporting as CSV, it is not highlighted in colour, but it would allow users to work with the comparison and the translations at the same time.

**Comment by pakoselo** [comment]
Again, it never come to the discussion with us, and we need more context what and how (we didn't ask why as this is the request from user community) it should be done. As uou can see it was asigned to Maja (again when Taina left, but it was never discussed with us). Also adding @Stifo to the discussion.
