### ISSUE TITLE
SKOS exports need to be valid

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#331]
**Original report on BitBucket by Carsten Thiel (GitHub: [schildwaechter](https://github.com/schildwaechter)).**

----------------------------------------

SKOS exports must be valid SKOS files, validate against [https://github.com/NatLibFi/Skosify](https://github.com/NatLibFi/Skosify)

**Comment by john-shepherdson** [comment]
Checked 3 CVs exported in SKOS format, using W3C validation service (https://www.w3.org/RDF/Validator/rdfval).

1. DDI-A Aggregation method (source and target languages)
2. CESSDA Topic Classification (source language only, file to large to parse if all target languages included)
3. GESIS Rexconcepts (source and target languages)

All three validated successfully.
