### ISSUE TITLE
No semantics in the URIs

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#333]
**Original report on BitBucket by Carsten Thiel (GitHub: [schildwaechter](https://github.com/schildwaechter)).**

----------------------------------------

No semantics in the URI!!

Exception for the version:

* Must be optional, deliver latest by default  
  \(data for v2 should mention v1 - provenance\)
* languages can not be independently versioned

Related issue #358.

‌

**Comment by MajaDolinar** [comment]
Closing, resolved in #455
