### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#336]
**Original report on BitBucket by CESSDA Support Team (GitHub: [cessda](https://github.com/cessda)).**

----------------------------------------

This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Rate-Limited

These updates are currently rate-limited.

 - Update dependency com.itextpdf:html2pdf to v4.0.5
 - Update dependency io.spring.nohttp:nohttp-checkstyle to v0.0.11
 - Update dependency org.apache.maven.plugins:maven-failsafe-plugin to v3.0.0-M9
 - Update dependency org.apache.maven.plugins:maven-surefire-plugin to v3.0.0-M9
 - Update dependency org.docx4j:docx4j-JAXB-ReferenceImpl to v8.3.9
 - Update dependency webdriver-manager to v12.1.9
 - Update dependency @&zwnj;types/selenium-webdriver to v4.1.12
 - Update dependency browser-sync to v2.28.1
 - Update dependency com.github.alexcojocaru:elasticsearch-maven-plugin to v6.26
 - Update dependency com.google.cloud.tools:jib-maven-plugin to v3.3.1
 - Update dependency com.puppycrawl.tools:checkstyle to v9.3
 - Update dependency jest-junit to v13.2.0
 - Update dependency lint-staged to v12.5.0
 - Update dependency maven to v3.9.0
 - Update dependency org.apache.maven.plugins:maven-checkstyle-plugin to v3.2.1
 - Update dependency org.apache.maven.plugins:maven-clean-plugin to v3.2.0
 - Update dependency org.apache.maven.plugins:maven-compiler-plugin to v3.11.0
 - Update dependency org.apache.maven.plugins:maven-enforcer-plugin to v3.2.1
 - Update dependency org.apache.maven.plugins:maven-javadoc-plugin to v3.5.0
 - Update dependency org.apache.maven.plugins:maven-resources-plugin to v3.3.0
 - Update dependency org.docx4j:docx4j-ImportXHTML to v8.3.8
 - Update dependency org.jsoup:jsoup to v1.15.4
 - Update dependency prettier to v2.8.4
 - Update dependency sass to v1.58.3
 - Update dependency tslib to v2.5.0
 - Update dependency webpack-notifier to v1.15.0
 - Update mapstruct monorepo to v1.5.3.Final (`org.mapstruct:mapstruct-processor`, `org.mapstruct:mapstruct`)
 - Update Font Awesome to v6 (major) (`@&zwnj;fortawesome/fontawesome-svg-core`, `@&zwnj;fortawesome/free-solid-svg-icons`)
 - Update angular monorepo to v15 (major) (`@&zwnj;angular/animations`, `@&zwnj;angular/common`, `@&zwnj;angular/compiler`, `@&zwnj;angular/compiler-cli`, `@&zwnj;angular/core`, `@&zwnj;angular/forms`, `@&zwnj;angular/localize`, `@&zwnj;angular/platform-browser`, `@&zwnj;angular/platform-browser-dynamic`, `@&zwnj;angular/router`)
 - Update angular-cli monorepo to v15 (major) (`@&zwnj;angular/cli`, `@&zwnj;ngtools/webpack`)
 - Update archunit-junit5.version to v1 (major) (`com.tngtech.archunit:archunit-junit5-engine`, `com.tngtech.archunit:archunit-junit5-api`)
 - Update dependency @&zwnj;angular/cdk to v15
 - Update dependency @&zwnj;ng-bootstrap/ng-bootstrap to v14
 - Update dependency @&zwnj;openapitools/openapi-generator-cli to v2
 - Update dependency @&zwnj;swimlane/ngx-charts to v20
 - Update dependency @&zwnj;types/node to v18
 - Update dependency bootstrap to v5
 - Update dependency com.puppycrawl.tools:checkstyle to v10
 - Update dependency copy-webpack-plugin to v11
 - Update dependency eslint to v8
 - Update dependency eslint-config-prettier to v8
 - Update dependency generator-jhipster to v7
 - Update dependency html-loader to v4
 - Update dependency husky to v8
 - Update dependency jest-junit to v15
 - Update dependency jest-preset-angular to v13
 - Update dependency lint-staged to v13
 - Update dependency maven-wrapper to v3
 - Update dependency merge-jsons-webpack-plugin to v2
 - Update dependency mocha to v10 (`mocha`, `@&zwnj;types/mocha`)
 - Update dependency ngx-chips to v3
 - Update dependency ngx-cookie-service to v15
 - Update dependency ngx-infinite-scroll to v15
 - Update dependency ngx-quill to v20
 - Update dependency ngx-webstorage to v11
 - Update dependency org.docx4j:docx4j-ImportXHTML to v11
 - Update dependency org.docx4j:docx4j-JAXB-ReferenceImpl to v11
 - Update dependency org.docx4j:docx4j-core to v11
 - Update dependency org.glassfish.jaxb:jaxb-runtime to v4
 - Update dependency org.hibernate:hibernate-jpamodelgen to v6
 - Update dependency postcss-loader to v7
 - Update dependency rimraf to v4
 - Update dependency rxjs to v7
 - Update dependency sass-loader to v13
 - Update dependency simple-progress-webpack-plugin to v2
 - Update dependency style-loader to v3
 - Update dependency swagger-ui-dist to v4
 - Update dependency terser-webpack-plugin to v5
 - Update dependency thread-loader to v3
 - Update dependency ts-loader to v9
 - Update dependency ts-node to v10
 - Update dependency typescript to v4
 - Update dependency webpack to v5
 - Update dependency webpack-bundle-analyzer to v4
 - Update dependency webpack-cli to v5
 - Update dependency webpack-dev-server to v4
 - Update dependency webpack-merge to v5
 - Update dependency workbox-webpack-plugin to v6
 - Update jest monorepo to v29 (major) (`@&zwnj;types/jest`, `jest`)
 - Update spring boot to v3 (major) (`org.springframework.boot:spring-boot-maven-plugin`, `org.springframework.boot:spring-boot-configuration-processor`)
 - Update typescript-eslint monorepo to v5 (major) (`@&zwnj;typescript-eslint/eslint-plugin`, `@&zwnj;typescript-eslint/eslint-plugin-tslint`, `@&zwnj;typescript-eslint/parser`)
 - [ ] 🔐 **Create all rate-limited PRs at once** 🔐

---

### ⚠ Dependency Lookup Warnings ⚠

-   Renovate failed to look up the following dependencies: `org.eclipse.m2e:lifecycle-mapping`.

Files affected: `pom.xml`

---

## Open

These updates have all been created already.

 - [Update dependency bootstrap to v4.6.2](../../pull-requests/225)
 - [Update dependency org.docx4j:docx4j-core to v8.3.9](../../pull-requests/229)
 - [Update dependency org.glassfish.jaxb:jaxb-runtime to v2.3.8](../../pull-requests/230)
 - [Update dependency org.hibernate:hibernate-jpamodelgen to v5.6.15.Final](../../pull-requests/239)
 - [Update dependency org.jboss.xnio:xnio-all to v3.8.8.Final](../../pull-requests/240)
 - [Update dependency postcss to v8.4.21](../../pull-requests/241)
 - [Update archunit-junit5.version to v0.23.1](../../pull-requests/242) (`com.tngtech.archunit:archunit-junit5-engine`, `com.tngtech.archunit:archunit-junit5-api`)
 - [Update dependency @&zwnj;fortawesome/angular-fontawesome to v0.12.1](../../pull-requests/243)
 - [Update dependency zone.js to v0.12.0](../../pull-requests/181)
 - [Update spring boot to v2.7.9](../../pull-requests/86) (`org.springframework.boot:spring-boot-maven-plugin`, `org.springframework.boot:spring-boot-configuration-processor`)
 

## Ignored or Blocked

These are blocked by an existing closed PR and will not be recreated.

 - [Update dependency @&zwnj;ngx-translate/core to v14](../../pull-requests/92)
 - [Update dependency @&zwnj;ngx-translate/http-loader to v7](../../pull-requests/93)
 - [Update dependency css-loader to v6](../../pull-requests/103)
 - [Update dependency html-webpack-plugin to v5](../../pull-requests/108)
 - [Update dependency mini-css-extract-plugin to v2](../../pull-requests/113)

## Detected dependencies

**maven**

**pom.xml**

 - `io.github.jhipster:jhipster-dependencies 3.9.1`
 - `org.jboss.xnio:xnio-all 3.8.7.Final`
 - `org.mapstruct:mapstruct 1.4.2.Final`
 - `org.mapstruct:mapstruct-processor 1.4.2.Final`
 - `de.dentrassi.elasticsearch:log4j2-mock 0.0.2`
 - `com.tngtech.archunit:archunit-junit5-api 0.22.0`
 - `com.tngtech.archunit:archunit-junit5-engine 0.22.0`
 - `com.itextpdf:html2pdf 4.0.4`
 - `org.docx4j:docx4j-ImportXHTML 8.2.1`
 - `org.docx4j:docx4j-core 8.3.7`
 - `org.docx4j:docx4j-JAXB-ReferenceImpl 8.3.8`
 - `org.imgscalr:imgscalr-lib 4.2`
 - `org.jsoup:jsoup 1.14.3`
 - `com.github.alexcojocaru:elasticsearch-maven-plugin 6.19`
 - `com.mycila:license-maven-plugin 4.1`
 - `org.apache.maven.plugins:maven-release-plugin 2.5.3`
 - `org.apache.maven.plugins:maven-checkstyle-plugin 3.1.2`
 - `com.puppycrawl.tools:checkstyle 9.1`
 - `io.spring.nohttp:nohttp-checkstyle 0.0.10`
 - `org.apache.maven.plugins:maven-compiler-plugin 3.8.1`
 - `org.springframework.boot:spring-boot-configuration-processor 2.2.7.RELEASE`
 - `org.mapstruct:mapstruct-processor 1.4.2.Final`
 - `org.hibernate:hibernate-jpamodelgen 5.6.9.Final`
 - `org.glassfish.jaxb:jaxb-runtime 2.3.6`
 - `org.apache.maven.plugins:maven-javadoc-plugin 3.3.1`
 - `org.apache.maven.plugins:maven-war-plugin 3.3.2`
 - `com.github.eirslett:frontend-maven-plugin 1.12.1`
 - `pl.project13.maven:git-commit-id-plugin 4.9.10`
 - `org.jacoco:jacoco-maven-plugin 0.8.8`
 - `com.google.cloud.tools:jib-maven-plugin 3.1.4`
 - `org.apache.maven.plugins:maven-clean-plugin 3.1.0`
 - `org.apache.maven.plugins:maven-eclipse-plugin 2.10`
 - `org.apache.maven.plugins:maven-enforcer-plugin 3.0.0`
 - `org.apache.maven.plugins:maven-idea-plugin 2.2.1`
 - `org.apache.maven.plugins:maven-resources-plugin 3.2.0`
 - `org.apache.maven.plugins:maven-surefire-plugin 3.0.0-M7`
 - `org.apache.maven.plugins:maven-failsafe-plugin 3.0.0-M7`
 - `org.sonarsource.scanner.maven:sonar-maven-plugin 3.9.1.2184`
 - `org.springframework.boot:spring-boot-maven-plugin 2.2.7.RELEASE`
 - `org.mapstruct:mapstruct-processor 1.4.2.Final`
 - `org.eclipse.m2e:lifecycle-mapping 1.0.0`

**maven-wrapper**

**.mvn/wrapper/maven-wrapper.properties**

 - `maven 3.6.3`
 - `maven-wrapper 0.5.6`

**npm**

**package.json**

 - `@&zwnj;angular/animations 10.2.5`
 - `@&zwnj;angular/cdk 10.2.7`
 - `@&zwnj;angular/common 10.2.5`
 - `@&zwnj;angular/compiler 10.2.5`
 - `@&zwnj;angular/core 10.2.5`
 - `@&zwnj;angular/forms 10.2.5`
 - `@&zwnj;angular/localize 10.2.5`
 - `@&zwnj;angular/platform-browser 10.2.5`
 - `@&zwnj;angular/platform-browser-dynamic 10.2.5`
 - `@&zwnj;angular/router 10.2.5`
 - `@&zwnj;fortawesome/angular-fontawesome 0.7.0`
 - `@&zwnj;fortawesome/fontawesome-svg-core 1.2.36`
 - `@&zwnj;fortawesome/free-solid-svg-icons 5.15.4`
 - `@&zwnj;ng-bootstrap/ng-bootstrap 6.2.0`
 - `@&zwnj;ngx-translate/core 13.0.0`
 - `@&zwnj;ngx-translate/http-loader 6.0.0`
 - `@&zwnj;swimlane/ngx-charts 16.0.0`
 - `bootstrap 4.6.1`
 - `moment 2.29.4`
 - `ng-jhipster 0.16.0`
 - `ngx-chips 2.2.2`
 - `ngx-cookie-service 3.1.3`
 - `ngx-infinite-scroll 10.0.1`
 - `ngx-quill 12.0.1`
 - `ngx-text-diff 0.6.0`
 - `ngx-webstorage 5.0.0`
 - `quill 2.0.0-dev.4`
 - `quill-better-table 1.2.10`
 - `quill-blot-formatter 1.0.5`
 - `rxjs 6.6.7`
 - `swagger-ui-dist 3.52.5`
 - `tslib 2.3.1`
 - `zone.js 0.11.4`
 - `@&zwnj;angular/cli 10.2.4`
 - `@&zwnj;angular/compiler-cli 10.2.5`
 - `@&zwnj;ngtools/webpack 10.2.4`
 - `@&zwnj;openapitools/openapi-generator-cli 1.0.13-4.3.1`
 - `@&zwnj;types/chai 4.3.4`
 - `@&zwnj;types/chai-string 1.4.2`
 - `@&zwnj;types/jest 26.0.24`
 - `@&zwnj;types/mocha 7.0.2`
 - `@&zwnj;types/node 13.13.4`
 - `@&zwnj;types/selenium-webdriver 4.0.16`
 - `@&zwnj;typescript-eslint/eslint-plugin 2.34.0`
 - `@&zwnj;typescript-eslint/eslint-plugin-tslint 2.34.0`
 - `@&zwnj;typescript-eslint/parser 2.34.0`
 - `autoprefixer 10.4.13`
 - `browser-sync 2.27.10`
 - `browser-sync-webpack-plugin 2.3.0`
 - `chai 4.3.7`
 - `chai-as-promised 7.1.1`
 - `chai-string 1.5.0`
 - `codelyzer 6.0.2`
 - `copy-webpack-plugin 6.4.1`
 - `css-loader 3.6.0`
 - `eslint 6.8.0`
 - `eslint-config-jhipster 0.0.1`
 - `eslint-config-prettier 6.15.0`
 - `eslint-loader 4.0.2`
 - `file-loader 6.2.0`
 - `friendly-errors-webpack-plugin 1.7.0`
 - `generator-jhipster 6.10.5`
 - `html-loader 1.3.2`
 - `html-webpack-plugin 4.5.2`
 - `husky 4.3.8`
 - `jest 26.6.3`
 - `jest-date-mock 1.0.8`
 - `jest-junit 13.0.0`
 - `jest-preset-angular 8.4.0`
 - `jest-sonar-reporter 2.0.0`
 - `lint-staged 12.3.4`
 - `merge-jsons-webpack-plugin 1.0.21`
 - `mini-css-extract-plugin 1.6.2`
 - `mocha 8.4.0`
 - `moment-locales-webpack-plugin 1.2.0`
 - `optimize-css-assets-webpack-plugin 6.0.1`
 - `postcss 8.4.6`
 - `postcss-loader 4.3.0`
 - `prettier 2.4.1`
 - `protractor 7.0.0`
 - `reflect-metadata 0.1.13`
 - `rimraf 3.0.2`
 - `sass 1.43.5`
 - `sass-loader 8.0.2`
 - `simple-progress-webpack-plugin 1.1.2`
 - `style-loader 1.3.0`
 - `terser-webpack-plugin 3.1.0`
 - `thread-loader 2.1.3`
 - `to-string-loader 1.2.0`
 - `ts-loader 7.0.5`
 - `ts-node 8.10.2`
 - `tslint 6.1.3`
 - `typescript 3.9.10`
 - `webdriver-manager 12.1.8`
 - `webpack 4.46.0`
 - `webpack-bundle-analyzer 3.9.0`
 - `webpack-cli 3.3.12`
 - `webpack-dev-server 3.11.3`
 - `webpack-merge 4.2.2`
 - `webpack-notifier 1.14.1`
 - `workbox-webpack-plugin 5.1.4`
 - `write-file-webpack-plugin 4.5.1`
 - `node >=12.16.1`

**Comment by matthew-morris-cessda** [comment]
Renovate Bot is no longer in use
