### ISSUE TITLE
Language choice in search navigation

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#355]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

Determine what language choices remain. The default is English but the user can choose another language from the dropdown list beside the search box. This dropdown language choice is kept when navigating with arrows.

However, when the user changes the vocabulary language from the two-letter language box in the results list or detailed study view, this choice disappears when navigating and the search language choice overrides it.

Is this how we want the system to work? Determine with other users and put an issue if needed.

‌

**Comment by MajaDolinar** [comment]
To be discussed sometime in the future with the user group.
