### ISSUE TITLE
Design: URI requirements for DDI vocabularies

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#358]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

1. Persistent URI for the vocabulary
2. Persistent URI for each concept - not based on changeable code value, need to have a concept level URIs.

‌

**Recommendations for DDI URIs**

Recommended concept URI where the last '1' refers to the persistent concept ID:

* [https://ddialliance.org/Specification/DDI-CV/AggregationMethod/1.1/1](https://ddialliance.org/Specification/DDI-CV/AggregationMethod/1.1/1)

‌

Other recommendations:

* URIs should not reference HTML or anchor tags

e.g. not [https://ddialliance.org/Specification/DDI-CV/AggregationMethod\_1.1.html#Sum](https://ddialliance.org/Specification/DDI-CV/AggregationMethod_1.1.html#Sum)

* Do not use natural language labels in URIs

e.g. not [https://ddialliance.org/Specification/DDI-CV/AggregationMethod\_1.1.html#Sum](https://ddialliance.org/Specification/DDI-CV/AggregationMethod_1.1.html#Sum)

* Partition URIs with /  with a predictable syntax

e.g. not [_https://ddialliance.org/Specification/DDI-CV/AggregationMethod\_1.1.html#_](https://ddialliance.org/Specification/DDI-CV/AggregationMethod_1.1.html#Sum)_Sum_

To be discussed: do DDI vocabularies have only DDI URIs or also CVS URIs? Probably DDI URIs is enough?

Related issue #333.

**Comment by MajaDolinar** [comment]
Closing, resolved in #455
