### ISSUE TITLE
Keep place when editing

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#367]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

When the user does some code changes \(adds a code, deletes a code, or in TL adds a translation for a code or edits a translation\):

* After clicking on ‘Save’ the system returns the user to the top of the code list
* If the code list is long, the user may need to scroll back to where they were many times

This is annoying, e.g., for translators who are translating CVs with many terms. 

Can the system be made to keep place in the list after the user has saved?

‌

**Comment by MajaDolinar** [comment]
Not really important at this point, will be reopened if some users complain about this issue. Closing for now
