### ISSUE TITLE
Extend URI variables for DDI Alliance purposes

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#368]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

Currently, there is a mechanism to define the URIs within a vocabulary by a pattern string, which contains some variables to specify certain identification parts for a specific vocabulary. The DDI Alliance needs an extension of this set of possible variables. 

The set of variables already consists of:

* \[VOCABULARY\] for the vocabulary notation string
* \[LANGUAGE\] for the target language
* \[VERSION\] for the version of a given vocabulary
* \[CODE\] for the code of a given concept in a given vocabulary.

The actual creation of a URI is implemented as a method within _eu.cessda.cvs.utils.VocabularyUtils_ named _generateURI\(\)_. Currently, all values for generating a specific URI are handed over as individual strings.

The first change would therefore be to change the signature of this method. I would like to hand over references to the Version instance and the Concept instance \(null in case of the vocabulary URIs\). This will cause a change at all places, which call this method of course. The instances should be accessible directly there, so that we don't need to change other behaviours. This will make any future extension of the URI-pattern just a matter of changing this method internally.

The second change would be just inside the _generateURI\(\)_ method, to extend the set of variables for the pattern by \[CODEID\]  and \[VOCABULARYID\] to use their internal DB-ID \(database IDs\) for the URIs.

**Comment by MajaDolinar** [comment]
Closing, resolved in #455
