### ISSUE TITLE
System Audit for Registered Users´ Events

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#378]
**Original report on BitBucket by Joshua Tetteh Ocansey (GitHub: [Joshocan](https://github.com/Joshocan)).**

----------------------------------------

Record logs or audits for events triggered by registered users including Editors. 

 At the moment there are some audits for [Authentication events](https://vocabularies-staging.cessda.eu/admin/audits?page=2&sort=auditEventDate,desc) such as creating, editing, and deleting SL and TL, etc. 

‌

**Comment by Lorenz1983** [comment]
@pakoselo Has the issue really been resolved? If so, then I can close it.

**Comment by pakoselo** [comment]
@Lorenz1983 it should be, but somebody should review it as it is already deployed: https://vocabularies-dev.cessda.eu/admin/audits you can see how it works and looks.
