### ISSUE TITLE
Design: SKOS/RDF amendment

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#387]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

This is the issue to handle changes to SKOS/RDF.

Process:

* Taina to produce a short multilingual example vocabulary, with versions 1.0 and 2.0. Done, Excel doc attached.
* Darren to produce an example SKOS/RDF of the vocabulary versions for IISAS and attach here. 
* IISAS to communicate with Oliver and Darren to amend the SKOS/RDF.
* The end result must be valid according to SKOS validation tools such as skosify. See #331.

‌

**Comment by MajaDolinar** [comment]
Closing, resolved.
