### ISSUE TITLE
Deprecation in CSV export

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#426]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

Add deprecation information into CSV export.

Not sure if the problem noted in #219 is relevant here.

This is on hold till the top priority issues are resolved, not a priority issue.

**Comment by Stifo** [comment]
@MajaDolinar 
It's unclear what information regarding deprecation should be exported. Please provide an example.

**Comment by MajaDolinar** [comment]
Closing the issue.
