### ISSUE TITLE
'Ready' TL pop-up when one SL version untranslated

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#442]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

In a situation where:

1. Published CV contains SL and TL \(v 1.0\)
2. New SL version is produced \(v2.0\), TL remains draft, it is never put into status ‘Ready to be translated’. SL v. 2.0 is published without updated TL.
3. New SL version is produced \(v. 3.0\). The system produces the TL draft from v. 2.0.
4. Now TL is translated for v. 3.0. When the TL hops over one SL version, the system does not produce change logs and comparison table. However, the translator will have to produce the version history manually, by comparing the TL from 1.0 and TL from 3.0.

‌

For the translator to produce the version history, they need to have the fields to enter this information.

Change needed for the pop-up for changing TL status change to ‘Ready to be published’ in this particular case:

* Add ‘Version notes’ and ‘Version changes’ elements that the TL admin can edit.
* Place between License and Version number

‌

Current pop-up

![](https://bitbucket.org/repo/A6bqkay/images/2823246299-image.png)
‌

‌

‌

I  hope this is not very complicated to code \(i.e. to determine the case when this pop-up appears\).

**Comment by Lorenz1983** [comment]
@Stifo Please implement it.

**Comment by Stifo** [comment]
This was before the new versioning system implementation and subsequent workflow adjustments.
