### ISSUE TITLE
Comparison table should not include changes from all versions

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#453]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

It seems that the comparison table has now changed to include changes made to the vocabulary in any version.

The comparison table should only include: 

* Changes between the current version and the previous published version in that language.
*  The current version is the latest Editor version and in the general UI the latest published version

As SL Admin, I created a new version of TestingCV2 \(en\). I added a definition to Code10.

In the ‘Ready to translate SL \[language code\]’ pop-up the change log only included this change but the comparison table included the changes from all the previous versions as well.

‌

![](https://bitbucket.org/repo/A6bqkay/images/2427567072-image.png)
‌

The fix is: include in the comparison table only the changes made in the Editor to the new version. This means the same changes that are displayed in the change log.

This applies also to TL ‘Ready to be published’ pop-up and the language specific comparison tables of published versions.

Not sure if this issue came up because of he work done on the versioning.

**Comment by Stifo** [comment]
don't know, why this issue came up as it was already solved by ae5259a861367872e3553d6f69a32e743a5b174d. closing.
