### ISSUE TITLE
CVS application is unavailable - 503 error

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#454]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

## As at 2022-11-09 17:08:09 CET

cvs-frontend-0 pod is unstable. Many restarts. Logs say:  
`Wrapped by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'vocabularyServiceImpl' defined in file [/app/classes/eu/cessda/cvs/service/impl/VocabularyServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 10; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vocabularyEditorSearchRepository': Invocation of init method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: mapper [titleLt.Key] of different type, current_type [keyword], merged_type [icu_collation_keyword]I deleted the cvs-frontend-0 pod. I was reinstantiated but failed with same error.`

I deleted the cvs-frontend-0 pod. It was automatically reinstantiated but failed with same error.

Status is:

`back-off 5m0s restarting failed container=frontend pod=cvs-frontend-0_cvs(f85fb86f-88a0-476a-aca3-266582b03ba4): CrashLoopBackOff`

**Comment by matthew-morris-cessda** [comment]
This incident has been resolved
