### ISSUE TITLE
Add 'Code definition added' to change types

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#456]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

In the code editing pop-up \(both SL and TL\),  ‘Code definition added’ option is missing from the change types drop-down list.

Should then go to the change log, comparison table and be copied to Version changes in the ‘Ready to be translated’ \(SL\) and ‘Ready to publish’ \(TL\) pop-ups.

**Comment by pakoselo** [comment]
@MajaDolinar what's the status of this request? It is marked as a duplicate, but in the #432 issue, is written, that it should be discussed with DDI CVG. Anoher thing is that I don't understand what to do? I got the first part: "In the code editing pop-up (both SL and TL), ‘Code definition added’ option is missing from the change types drop-down list.", but not the second one: "Should then go to the change log, comparison table and be copied to Version changes in the ‘Ready to be translated’ (SL) and ‘Ready to publish’ (TL) pop-ups.". What does it mean?

**Comment by MajaDolinar** [comment]
@pakoselo add the 'Code definition added' option to the change types drop-down list.
![Screenshot 2023-04-26 at 21 46 58](https://user-images.githubusercontent.com/72601736/234686284-80744da9-6a3b-44a7-9352-cfc7e14b3e8a.png)

The second part refers to the established workflow that follows after this, I don't think you need to change anything there, I believe that Taina just wanted to make sure that this additional option of the drop-down list appears also everywhere that other change types appear (so the change log, comparison table and in the description of Version changes).

**Comment by pakoselo** [comment]
@MajaDolinar Now I got it, thanks. In few hours (1-2), it should be visible on stagging or/and dev.

**Comment by MajaDolinar** [comment]
I do not see this yet on staging or dev so I cannot test.

**Comment by pakoselo** [comment]
@MajaDolinar maybe I forgot to merge it to the master. I will check and get back to you.

**Comment by pakoselo** [comment]
@MajaDolinar My fault I added it here 
![image](https://user-images.githubusercontent.com/7714766/235940840-c4f97f3c-dc0e-4abe-851f-c4137b316392.png)
I didn't think of it as a change in the Edit code for TL, but as a change for SL. I will move it to the Edit code. My question is. Should it be visible only for TL, or also for SL. e.g. user add new code (in SL) and when click on the Edit code, can be added this Change note. Or only for SL?

**Comment by MajaDolinar** [comment]
It should be visible to both TL and SL.

**Comment by pakoselo** [comment]
@MajaDolinar it was merged with the master. In few minutes, it should be deployed on dev and stagging.

**Comment by pakoselo** [comment]
@MajaDolinar just one comment. It doesn't make much sense to have it in the edit dialog to me, maybe it should be only in add dialog of the SL version. Of course only if it's not initial one. And maybe in the edit in TL. But this will change the situation little bit and will be more complicated to achieve.

**Comment by MajaDolinar** [comment]
Looks good for now. I am closing this issue and will keep your comment for further consideration.
