### ISSUE TITLE
TL change logs and 'Version changes' content

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#458]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

Only SL change logs seem to be copied to TL change logs.

* I created a new SL version of the just published vocabulary COVIDCA and made two change. Moved status to ‘Ready to be translated’. Change log was copied to ‘Version changes’ in the pop-up.
* I created a new version of the FI TL as ADMIN\_TL. Changed a code descriptive term. Moved status to ‘Ready to be published'. The pop-up only copied SL changes from the change log to the TL pop-up ‘Version changes’ field. In the change log, you can see 3 changes, of which one in TL.

‌

![](https://bitbucket.org/repo/A6bqkay/images/3148840548-image.png)
‌

**Comment by pakoselo** [comment]
@MajaDolinar I am not sure I got the problem. Images are missing. I tried to create new version of SL, with changing the code definition and adding new code and it also shows the later change (add code) in the TL. Can you please elaborate it little bit more?

**Comment by MajaDolinar** [comment]
Yes, I am also having trouble reproducing this and understanding what the issue behind this is. That is why I haven’t provided you with screenshots yet.  I will investigate further and hopefully clarify this in the coming days.

**Comment by MajaDolinar** [comment]
I do not understand what this issue is about. Closing the issue for now, will not be worked on.
