### ISSUE TITLE
Change tab name - license and citation

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#459]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

Change the tab name from ‘License and Citation’ to ‘License and citation’ in detailed vocabulary view in the UI, to be in line with the other tabs.

Maja to decide first if it is changed to ‘Licence and citation’, i.e. to British instead of American spelling.

**Comment by MajaDolinar** [comment]
Change the tab name from ‘License and Citation’ to ‘Licence and citation’

**Comment by Stifo** [comment]
Will be fixed with merged PR #570.

**Comment by MajaDolinar** [comment]
Ready for 3.1.0 release
