### ISSUE TITLE
Database changes for 3.0.0 migration.

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#464]
**Original report on BitBucket by Martin Bobak.**

----------------------------------------

IISAS \(@pakoselo together with @&zwnj;Martin Bobak and @Stifo \) will provide a script which needs to be executed on testing  and production instances before the next version deployment.

@john-shepherdson and @Joshocan please inform us when the script was executed on the testing and later on production instances.

**Comment by Joshocan** [comment]
Migrated and tested!  For eg. Contributor_SL and Contributor_TL have been removed as roles from Production.
