### ISSUE TITLE
Fix deprecation warnings in Jenkins build - cessda.cvs.contentguide

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#467]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

> DEPRECATION WARNING: Using / for division outside of calc\(\) is deprecated and will be removed in Dart Sass 2.0.0.
> 
> Recommendation: math.div\($nav-list-item-height-sm, 4\) or calc\($nav-list-item-height-sm / 4\)
> 
> More info and automated migrator: https://sass-lang.com/d/slash-div

See [https://jenkins.cessda.eu/view/CVS/job/cessda.cvs.contentguide/job/386-Amendments-to-editor-user-guide-for-v3-0-0/4/console](https://jenkins.cessda.eu/view/CVS/job/cessda.cvs.contentguide/job/386-Amendments-to-editor-user-guide-for-v3-0-0/4/console)

**Comment by matthew-morris-cessda** [comment]
Fixed with the release of [cessda.documentation.theme 0.1.9](https://github.com/cessda/cessda.documentation.theme/releases/tag/0.1.9)
