### ISSUE TITLE
Draft Agency Hosting Guideline

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#485]
**Original report on BitBucket by Joshua Tetteh Ocansey (GitHub: [Joshocan](https://github.com/Joshocan)).**

----------------------------------------

CVS is now in production therefore there should be a guideline on how a new agency would be able to register and host their vocabularies on the CVS system.

**Comment by Joshocan** [comment]
https://docs.google.com/document/d/1HNdn7slEUXs50TeLIxyeRdT6LP6GR0uMBhytVpps-y4/edit#heading=h.uc135qz6afqo

**Comment by Joshocan** [comment]
https://docs.google.com/document/d/1HNdn7slEUXs50TeLIxyeRdT6LP6GR0uMBhytVpps-y4/edit#heading=h.uc135qz6afqo
