### ISSUE TITLE
Regenerate citations and update version numbers inside

### ISSUE THREAD

**Issue by MajaDolinar** [cessda/cessda.cvs.two#555]
Citations currently do not display the proper version number. See image for details
![Citations_issue](https://user-images.githubusercontent.com/72601736/223094436-2075b6e5-73bb-44fc-9032-fca899b6d68f.PNG)

**Comment by MajaDolinar** [comment]
Have you executed this code on staging? It still does not correspond to version selected. Available from changes accordingly, whereas the Citation information does not change. 
![Screenshot 2023-04-03 at 10 12 07](https://user-images.githubusercontent.com/72601736/229451113-a8b7a644-4fd0-43c4-9367-a509360aa71c.png)

**Comment by john-shepherdson** [comment]
@matthew-morris-cessda can you take a look in Joshua's absence?

**Comment by MajaDolinar** [comment]
@matthew-morris-cessda and @john-shepherdson what is happening then with this part? I cannot close it and sign it for relelase if it is not done.

**Comment by matthew-morris-cessda** [comment]
@MajaDolinar I have run the script against CVS Staging, see attached screenshot

![image](https://user-images.githubusercontent.com/68543725/229727081-8a4794ee-17be-4316-b5c1-88a8e5ff8171.png)

**Comment by MajaDolinar** [comment]
Thank you @matthew-morris-cessda 
I see the issue is resolved, so I am closing this issue. Ready for 3.1.0 release.
