### ISSUE TITLE
"Cannonical URI" and "Available from" issue for latest version

### ISSUE THREAD

**Issue by MajaDolinar** [cessda/cessda.cvs.two#558]
When I click on the latest version of the CV the Available from shows undefined and Canonical URI is missing. If I choose a previous version they are showing. This is on production, however on staging it shows correctly also for latest version. 

See screenshots from production below:
![Screenshot 2023-03-08 at 05 47 48](https://user-images.githubusercontent.com/72601736/223622378-0fbce83c-3e7b-4a5b-ae9d-61b223fbd943.png)
![Screenshot 2023-03-08 at 05 49 35](https://user-images.githubusercontent.com/72601736/223622439-e3d22d5f-c056-41c1-a817-d48232b65313.png)
![Screenshot 2023-03-08 at 05 50 27](https://user-images.githubusercontent.com/72601736/223622625-6fc0c3f9-f3a9-48c5-ac88-4d8b5a150be2.png)
![Screenshot 2023-03-08 at 05 51 02](https://user-images.githubusercontent.com/72601736/223622634-4cdae17d-4848-43ea-96f1-2137cc681fa9.png)

**Comment by Stifo** [comment]
it looks like that [this script](https://github.com/cessda/cessda.cvs.two/issues/484#issuecomment-1450140639) was not executed over the production db. i'll check the production dump and come back then.

**Comment by MajaDolinar** [comment]
Great, so it is working now. Closing the issue
