### ISSUE TITLE
Cessda CV DP-R|EX: URL error

### ISSUE THREAD

**Issue by MajaDolinar** [cessda/cessda.cvs.two#560]
Gesis reported an issue with URL:
We have created a CV for our DP-R|EX metadata schema (https://vocabularies.cessda.eu/editor/vocabulary/DP-REX_Konzepte) which we have already published. Strangely, however, the URL link does not work.
https://vocabularies.cessda.eu/urn/urn:ddi:int.gesis.org:DP-REX_Konzepte:1.4.0
We always receive the following message: 'error page/this page does not exist'. 
Can you help us with this problem?

**Comment by pakoselo** [comment]
@MajaDolinar @Stifo @john-shepherdson @Joshua-cessda-admin As this CV was published yesterday (8.3.2023) and the DB is probably not in consistent state  (Stefan is looking at it) and to me it looks, like also the latest main branch is not deployed in the production. This is an outcome of this all issues together. I will investigate, why it's not working, but we will end by fixing the database after every change made by the users. Probably it will be better to follow the guidelines during major deployments (we need to deploy the code also with changes to DB). During 3.0.0. deployment, there were a special issue for that. I forgot the number. This is an endless loop we are getting into.

**Comment by pakoselo** [comment]
@MajaDolinar I solved the issue. The issue is that the name of the vocabulary is DP-REX_Konzepte, but the underscore is used for code definitions in the URI. It will work in editor as there are not such queries for codes implemented. So my opinion is to forbid the underscore '_' in the notation. On hack - how-to solve it, will be rename the CV (notation and in the URIs as well) in the DB and implement the code to forbid the underscore in the notation definition.

**Comment by MajaDolinar** [comment]
Yes, you are right, we have it in the Editor user guide to only use alphanumeric characters, as well as: ‘ + ‘ -’ ‘ : ‘ characters in CV short name. 
I will inform Gesis about this mistake and ask them to remove the underscore in the CV short name and the URI.

**Comment by pakoselo** [comment]
@MajaDolinar They will not be able to change it. Notation is forever, if I remember correctly. So we need to change it in the DB and change also the code not to allow it anymore to use underscore.

**Comment by MajaDolinar** [comment]
Yes I know, they can only delete this version and create a new one with the right notation - this is what I instructed them to do. However, you are right, we should disable this in the backend to now be able to publish in the future.

**Comment by pakoselo** [comment]
I had reopened the issue, as it is not solved in the code yet and also in the DB as there is no method to change the notation (IMHO).

**Comment by pakoselo** [comment]
There will be too much work, to recreate it once again. Probably it will be much more simpler to prepare one script (today) and execute it on production DB.

**Comment by MajaDolinar** [comment]
ok, if you think it will be simpler, then I will inform them that we are going to resolve this.

**Comment by pakoselo** [comment]
@Joshua-cessda-admin please execute this script on production mysql DB, so the CV will be reachable once again. Do not forget to build the indexes too in the maintenance section. It will basically replace all sequence "_Konzepte" with "-Konzepte" It was already tested locally.

`SET @SQL_SAFE_UPDATES=@@SQL_SAFE_UPDATES;
SET SQL_SAFE_UPDATES = 0;
#update notation
UPDATE cvs.vocabulary SET notation=REPLACE(notation, '_Konzepte' , '-Konzepte');

#update cannonical_uri in vocabularies
UPDATE cvs.vocabulary SET uri=REPLACE(uri, '_Konzepte' , '-Konzepte');

#update citation in versions
UPDATE cvs.version SET citation=REPLACE(citation, '_Konzepte' , '-Konzepte') WHERE vocabulary_id=(SELECT id FROM cvs.vocabulary where notation='DP-REX_Konzepte');

#update cannonical_uri in versions
UPDATE cvs.version SET canonical_uri=REPLACE(canonical_uri, '_Konzepte' , '-Konzepte') WHERE vocabulary_id=(SELECT id FROM cvs.vocabulary where notation='DP-REX_Konzepte');

#update uri in versions
UPDATE cvs.version SET uri=REPLACE(uri, '_Konzepte' , '-Konzepte') WHERE vocabulary_id=(SELECT id FROM cvs.vocabulary where notation='DP-REX_Konzepte');

#update uri_sl in versions
UPDATE cvs.version SET uri_sl=REPLACE(uri_sl, '_Konzepte' , '-Konzepte') WHERE vocabulary_id=(SELECT id FROM cvs.vocabulary where notation='DP-REX_Konzepte');

#update version_changes in versions
UPDATE cvs.version SET version_changes=REPLACE(version_changes, '_Konzepte' , '-Konzepte') WHERE vocabulary_id=(SELECT id FROM cvs.vocabulary where notation='DP-REX_Konzepte');

#update notation
UPDATE cvs.version SET notation=REPLACE(notation, '_Konzepte' , '-Konzepte') WHERE vocabulary_id=(SELECT id FROM cvs.vocabulary where notation='DP-REX_Konzepte');

#update vocabulary_change
UPDATE cvs.vocabulary_change SET description=REPLACE(description, '_Konzepte' , '-Konzepte');

#update concepts
UPDATE cvs.concept SET uri=REPLACE(uri, '_Konzepte' , '-Konzepte');

SET SQL_SAFE_UPDATES = @SQL_SAFE_UPDATES;`

**Comment by MajaDolinar** [comment]
this vocabulary exists only on production, so I cannot test on staging. The script needs to be run on production to see this resolve.

**Comment by MajaDolinar** [comment]
already implemented on production. Closing the issue
