### ISSUE TITLE
Resolved, On hold, Stale, Closed, othe states of the issues

### ISSUE THREAD

**Issue by pakoselo** [cessda/cessda.cvs.two#591]
Comparing to bitbucket, we have lost the resolve button for issues (not only this one, also other states are missing). Everything is in close, but it doesn't make sense.

**Comment by Joshocan** [comment]
@matthew-morris-cessda

**Comment by matthew-morris-cessda** [comment]
This can be acheived by using labels alongside the GitHub issue states (closed as completed; closed as not done). I've added labels for "Resolved" and "On hold". Please let us know if there are any more states that you would like.

**Comment by pakoselo** [comment]
Ok. Thanks for the explanation

> S pozdravom
> Martin Šeleng
> =====================
> Institute of Informatics
> Slovak Academy of Sciences
> Dubravska cesta 9
> 845 07 Bratislava
> Slovak Republic
> Tel: +421 (0)2 5941-1256
> Fax: +421 (0)2 5477-1004
> URL: ikt.ui.sav.sk
> E-mail: ***@***.*** ***@***.***>
