### ISSUE TITLE
Certificate expiry on production!

### ISSUE THREAD

**Issue by MajaDolinar** [cessda/cessda.cvs.two#595]
I am receiving a message on production that the certificate has expired. Please resolve this ASAP, it says that the securty certificate expired yesterday.

**Comment by MajaDolinar** [comment]
@john-shepherdson please assign to a person who is responsible for this. I am not sure

**Comment by john-shepherdson** [comment]
@matthew-morris-cessda this is urgent

**Comment by matthew-morris-cessda** [comment]
Fixed, the automatic Certbot scripts were renewing certificates as expeceted but were then attempting to build cessda.cvs.reverse/master which has since been renamed to cessda.cvs.reverse/main. This has been fixed for all CESSDA products.
