### ISSUE TITLE
Update CHANGELOG for 3.1.0

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cvs.two#596]

**Comment by matthew-morris-cessda** [comment]
Changelog draft created: https://github.com/cessda/cessda.cvs.two/releases/tag/untagged-9b4ec8a66d0780589827

**Comment by john-shepherdson** [comment]
Add DOI:

- [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.7795784.svg)](https://doi.org/10.5281/zenodo.7795784)
