### ISSUE TITLE
Update About page for version 3.1.0

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cvs.two#597]
Version number and release date

**Comment by matthew-morris-cessda** [comment]
Any example text, or do you just want the version number and release date changed?

**Comment by john-shepherdson** [comment]
I don't think there any user-facing changes, so just version number and date.

**Comment by john-shepherdson** [comment]
Maja has said that no changes are required to contents of either User Guide or Editors Guide

**Comment by john-shepherdson** [comment]
Has this been done?

**Comment by matthew-morris-cessda** [comment]
Not yet. I was going to release the code first, then update the about page.

**Comment by matthew-morris-cessda** [comment]
About page updated
