### ISSUE TITLE
CV location URI from DDI Alliance to CVS

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#63]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

The tool must allow the import of location URI from the DDI CV publication process, when such a process is launched.  How this is to be done will need to be discussed between Oliver, Claus-Peter and Wendy. DDI Alliance will publish the DDI CVs also on their own website.

CESSDA Vocabulary Service and DDI CV publication process will have different location URIs. Publication of a CV in different formats will also result in different URIs. Therefore, the element must be repeatable. 

To be discussed: will users need to see location URIs in the 'Identity and general tabs'?? There is a separate view for download.

**Comment by MajaDolinar** [comment]
Closing, resolved in #455
