### ISSUE TITLE
Add field(s) for external vocabulary info

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#64]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

Add a field in 'License and citation' tab for adding an external vocabulary name, owning agency and link. Optional information.

This may be needed if the vocabulary in the tool is wholly or partly based on an external vocabulary.

Not urgent.

**Comment by MajaDolinar** [comment]
Closing the issue.
