### ISSUE TITLE
Problems with Delete CV

### ISSUE THREAD

**Issue by pakoselo** [cessda/cessda.cvs.two#662]
@MajaDolinar Right now the Delete CV works that it tries to delete all versions with major.minor.x number, but this is not correct as every new translation creates whole new bundle also with patch number included. Actually this approach also breaks the whole system down. It should delete only bundle with major.minor.patch.

**Comment by pakoselo** [comment]
@MajaDolinar The delete functionality should be deployed on the dev/staging already. You can test it. Right now it should delete only whole bundle x.y.z (Sl with TL(s)) or of course only TL of specific version.

**Comment by MajaDolinar** [comment]
Closing, resolved.
