### ISSUE TITLE
Trouble accessing the second page

### ISSUE THREAD

**Issue by MajaDolinar** [cessda/cessda.cvs.two#669]
Somewhere between versions 3.1.0 and 3.2.0 it started to occur to me that the second page of the results list or the user list would not open. Upon clicking the second page, the first page would just reload. Even after clicking several times and refreshing the page the issue would remain. And then after some time, after clicking again the second page would finally open. 

I have noticed this issue on Safari browser, version 16.5. 
Also Taina reported having the same issues in Firefox, version 110.0

This issue is really hard to recreate, since it does not appear each time I am accessing the service, some days it occurs, some days it works fine. 
Please check if there is anything wrong on the service side or if this is only a browser issue.

- [ ] #818
- [ ] `ngb-pagination` issues - Licence Component
- [ ] `ngb-pagination` issues - Resolver Component
- [x] #819
- [ ] `ngb-pagination` issues - Comment Component
- [ ] `ngb-pagination` issues - Concept Component
- [ ] `ngb-pagination` issues - Metadata Field Component
- [ ] `ngb-pagination` issues - Metadata Value Component
- [ ] `ngb-pagination` issues - User Agency Component
- [ ] `ngb-pagination` issues - Version Component
- [ ] `ngb-pagination` issues - Vocabulary Component
- [ ] `ngb-pagination` issues - Vocabulary Change Component
- [x] `ngb-pagination` issues - Vocabulary Search Component

**Comment by MajaDolinar** [comment]
Closing, resolved.

**Comment by matthew-morris-cessda** [comment]
See #810

**Comment by matthew-morris-cessda** [comment]
This was reported as still occurring on 3.3.0

**Comment by matthew-morris-cessda** [comment]
I've managed to reproduce the issue, but nothing is logged in the browser's console when the problem occurs

**Comment by matthew-morris-cessda** [comment]
@MajaDolinar This is fixed on staging, please test and let me know if you find any issues

**Comment by MajaDolinar** [comment]
I tested on staging and it seems to be working on home, however on user management it does not work, it work the first time I tried to go on the second page and then it stopped, I am stuck on first page. 
https://vocabularies-staging.cessda.eu/admin/user-management?page=2&sort=id,asc

**Comment by matthew-morris-cessda** [comment]
Thanks @MajaDolinar for reporting back. This may occur for all components that use `ngb-pagination`. I've reopened this issue and have created a task list for assessing each use of `ngb-pagination`.

**Comment by pakoselo** [comment]
Hi all

Sorry for the late answer. We had a national holiday on Friday, so I was
out of Bratislava. Will look at it today and give feedback.

Cheers Martin

**Comment by matthew-morris-cessda** [comment]
@MajaDolinar The user management page should be fixed now

**Comment by MajaDolinar** [comment]
Yes, it seems to be working now as expected. Closing this issue. Can we have a release finished today?
