### ISSUE TITLE
dependency problem (since springfox upgrade?)

### ISSUE THREAD

**Issue by Stifo** [cessda/cessda.cvs.two#685]
build succeeded, but the app fails to start (due to swagger2?):

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.github.jhipster.config.apidoc.customizer.JHipsterSwaggerCustomizer.customize(JHipsterSwaggerCustomizer.java:89)

The following method did not exist:

    'com.google.common.base.Predicate springfox.documentation.builders.PathSelectors.regex(java.lang.String)'

The method's class, springfox.documentation.builders.PathSelectors, is available from the following locations:

    jar:file:/home/stevo/.m2/repository/io/springfox/springfox-core/2.10.5/springfox-core-2.10.5.jar!/springfox/documentation/builders/PathSelectors.class

It was loaded from the following location:

    file:/home/stevo/.m2/repository/io/springfox/springfox-core/2.10.5/springfox-core-2.10.5.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of springfox.documentation.builders.PathSelectors

**Comment by matthew-morris-cessda** [comment]
Ahh, Guava and SpringFox. Dependencies that cause endless trouble. I've created a PR that will revert this.

**Comment by Stifo** [comment]
there's still an ongoing deployment issue since [build #131](https://jenkins.cessda.eu/job/cessda.cvs.deploy/job/main/131/), which prevents to deploy and test new code on dev and staging:

```
Getting updates for unmanaged Helm repositories...
/home/jenkins/.local/share/helm/plugins/helm-gcs/scripts/pull.sh: 3: /home/jenkins/.local/share/helm/plugins/helm-gcs/bin/helm-gcs: not found
...Unable to get an update from the "gs://cessda-helm-repository/" chart repository:
	plugin "scripts/pull.sh" exited with error
Error: no cached repository for helm-manager-e9e07167a2d8ef16dbf94953db25bb69e4e5b28a29cd8c3632958ef45e62958e found. (try 'helm repo update'): open /tmp/.cache/helm/repository/helm-manager-e9e07167a2d8ef16dbf94953db25bb69e4e5b28a29cd8c3632958ef45e62958e-index.yaml: no such file or directory
```

**Comment by matthew-morris-cessda** [comment]
I've fixed this as well, and builds are deploying again.
