### ISSUE TITLE
Bad null characters at the end of the SKOS file

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cvs.two#702]
Reported by Jacco van Ossenbruggen, via https://helpdesk.cessda.eu/#ticket/zoom/3478
**Keep reporter updated of any developments**

Hi, something goes wrong at the end of the SKOS file served at https://vocabularies.cessda.eu/vocabulary/CountryNamesAndCodes?lang=en

And the end of the file, it closed properly with

</rdf:RDF>\n

But after the ending new line, a large (very large) null characters have been appended.

**Comment by matthew-morris-cessda** [comment]
![image](https://github.com/cessda/cessda.cvs.two/assets/68543725/6ef4af6d-4115-4768-9a99-1d6693dd5145)

**Comment by john-shepherdson** [comment]
Assign to IISAS?

**Comment by matthew-morris-cessda** [comment]
I'll take a look

**Comment by matthew-morris-cessda** [comment]
Fix has been verified

![image](https://github.com/cessda/cessda.cvs.two/assets/68543725/e64295be-cb0f-410b-97c4-71f9869092c5)
