### ISSUE TITLE
vocabulary download (SKOS) invalid xml

### ISSUE THREAD

**Issue by borsna** [cessda/cessda.cvs.two#778]
Steps to reproduce:

1. go to a vocabualry download page e.g: https://vocabularies.cessda.eu/vocabulary/DataType?lang=en
2. mark one ore more languages for download
3. resulting file have a line with null characters after `</rdf:RDF>`

![image](https://github.com/cessda/cessda.cvs.two/assets/794445/3e9aaf5b-9dfd-410c-9174-7136410b1dbe)

**Comment by matthew-morris-cessda** [comment]
@borsna This has been fixed in development

**Comment by matthew-morris-cessda** [comment]
See https://vocabularies-staging.cessda.eu/vocabulary/DataType?lang=en

**Comment by borsna** [comment]
@matthew-morris-cessda sorry about the duplication, did not find it as an open issue when i filed it.
