### ISSUE TITLE
Reload licence images

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cvs.two#796]
Licence logos are missing on dev and staging. 
See e.g. https://vocabularies-staging.cessda.eu/vocabulary/AnalysisUnit?lang=en or https://vocabularies-dev.cessda.eu/vocabulary/AnalysisUnit?lang=en

![Screenshot 2023-10-19 at 10 26 55](https://github.com/cessda/cessda.cvs.two/assets/107628491/e1aa4346-8c04-4279-aaef-30cf499084d4)

**Comment by matthew-morris-cessda** [comment]
These were lost due to not storing the images on persistent volumes, and need to be manually readded. They should persist once readded.

**Comment by john-shepherdson** [comment]
@MajaDolinar You need to reload the images via the UI (for both dev and staging).
Images are here: https://github.com/cessda/cessda.cvs.two/tree/main/src/main/webapp/content/images/license

**Comment by MajaDolinar** [comment]
Issue resolved. Closing.
