### ISSUE TITLE
API docs page is invalid

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cvs.two#797]
At the bottom right of the CVS API Swagger docs page, the validation icon says 'invalid'. Clicking on it leads to this page:
https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fvocabularies.cessda.eu%2Fv2%2Fapi-docs

Which display the following:

`{"messages":["attribute info.name is missing"],"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"required","message":"object has missing required properties ([\"name\"])","schema":{"loadingURI":"http://swagger.io/v2/schema.json#","pointer":"/definitions/license"},"instance":{"pointer":"/info/license"}}]}`

**Comment by matthew-morris-cessda** [comment]
Reproducable on staging, see <https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fvocabularies-staging.cessda.eu%2Fv2%2Fapi-docs>
