### ISSUE TITLE
Issue with Agency filter on Home

### ISSUE THREAD

**Issue by MajaDolinar** [cessda/cessda.cvs.two#809]
I go to Home and filter Agency to Gesis - the system works and filters out CVs of GESIS. I click on one GESIS vocabulary and then go back on Home, I try to filter again the Agency to Gesis and it does not work - the result shows all CVs.
@Stifo

related to #786

**Comment by pakoselo** [comment]
@MajaDolinar probably you need to index agencies. But we don't have the rights for that on production cluster.

**Comment by MajaDolinar** [comment]
@matthew-morris-cessda could you look at this please?

**Comment by matthew-morris-cessda** [comment]
I can reproduce the issue. It looks like the filter isn't applying correctly. Refreshing the page causes the page to look as expected.

When reproducing the issue the following is logged in the browser console

```text
ERROR TypeError: t.sort.split is not a function
    t https://vocabularies.cessda.eu/main-es2015.050e6681a22f60c9ecc0.js:1
    __tryOrUnsub https://vocabularies.cessda.eu/main-es2015.050e6681a22f60c9ecc0.js:1
    next https://vocabularies.cessda.eu/main-es2015.050e6681a22f60c9ecc0.js:1
    _next https://vocabularies.cessda.eu/main-es2015.050e6681a22f60c9ecc0.js:1
    next https://vocabularies.cessda.eu/main-es2015.050e6681a22f60c9ecc0.js:1
    _subscribe https://vocabularies.cessda.eu/main-es2015.050e6681a22f60c9ecc0.js:1
    _trySubscribe https://vocabularies.cessda.eu/main-es2015.050e6681a22f60c9ecc0.js:1
    _trySubscribe https://vocabularies.cessda.eu/main-es2015.050e6681a22f60c9ecc0.js:1
    subscribe https://vocabularies.cessda.eu/main-es2015.050e6681a22f60c9ecc0.js:1
    t https://vocabularies.cessda.eu/main-es2015.050e6681a22f60c9ecc0.js:1
    fac https://vocabularies.cessda.eu/main-es2015.050e6681a22f60c9ecc0.js:1
```

The production builds of CVS are minified, hence why `t` is a variable name, but if this can be reproduced locally then this should be debuggable.
