### ISSUE TITLE
Issues of accessing second page

### ISSUE THREAD

**Issue by MajaDolinar** [cessda/cessda.cvs.two#810]
It frequently happens that clicking the button to access the second page of various lists does not work. 
Please see if something can be done on this. 
This happens on several pages:
https://vocabularies.cessda.eu/?f=agency:GESIS&sort=code,asc&page=1
https://vocabularies.cessda.eu/admin/user-management

**Comment by pakoselo** [comment]
@MajaDolinar We don't have acces to management on the producton clsuter. Also the second page works for me on the production.

**Comment by MajaDolinar** [comment]
it comes and goes. I thought it only happens to me, but other people are also reporting this to me, so I don't know what the issue behind is.

**Comment by MajaDolinar** [comment]
@matthew-morris-cessda can you see also this please

**Comment by matthew-morris-cessda** [comment]
Duplicates #669
