### ISSUE TITLE
Release version 3.3.1

### ISSUE THREAD

**Issue by matthew-morris-cessda** [cessda/cessda.cvs.two#824]
This is a bugfix release to solve various pagination issues

- [x] Admins to redirect URL to 'service unavailable page' (if option is available)
- [x] Admins to backup production database, then run database update script (if required)

Release checklist: https://docs.google.com/spreadsheets/d/1KzLWKT7ZIPoQfBnuNYmqyex_fsASqASp3MUCLVp1ix8/edit#gid=238150674

Release report: https://docs.google.com/document/d/1jSrZurH78aMj588dXQwbsGFTnmHv9MaWW29_ukmhMDk/edit#heading=h.bxl4rzqycrnr

**Comment by MajaDolinar** [comment]
Approving the release.

**Comment by matthew-morris-cessda** [comment]
CVS 3.3.1 has been deployed

**Comment by MajaDolinar** [comment]
Great. I could edit the About page, so this is fixed now. I will do a bit of testing to see that all is ok.

**Comment by MajaDolinar** [comment]
On User Management page I cannot get to the second page - so this issue is still present here. It works on Home. 
Please check

**Comment by matthew-morris-cessda** [comment]
I cannot reproduce this. The page controls seem to work correctly.

![image](https://github.com/cessda/cessda.cvs.two/assets/68543725/19210f26-bee0-423c-b099-3a3093779e9c)

**Comment by MajaDolinar** [comment]
I go to user management and move between the 2 pages, it works fine. I click on Home and then go to user management again (select in menu). I try to access the 2 page, it moves to the second page. But then I want to move back to the first page and I cannot select the 1 page, it does not move. 
Only if you refresh it works again.

**Comment by matthew-morris-cessda** [comment]
I cannot get this to occur on my web browsers, despite me trying many different approaches.

**Comment by MajaDolinar** [comment]
Well it is like it always was for me: it comes and goes, so I really do not know at this point anymore. I guess we could officially announce that the release is done. At least on home it seems to not be occurring anymore, and on user management I can just refresh the page if it happens again and move on with it. 
I will write an email to the editors that the content is released again.

**Comment by MajaDolinar** [comment]
Email the editors about CVS being available again was sent:
"Dear CVS Editors,
this is to let you know that the CVS Editor is available again to you.
We have just released the 3.3.1 version of the CESSDA Controlled Vocabulary Service that includes some minor bug fixes and improvements. You can read all about the 3.1.0 release at the About page.
Kind regards,
Maja Dolinar
CVS Service Owner"

The DDI team was informed about the release as well.
