### ISSUE TITLE
Filter Audit Level UI

### ISSUE THREAD

**Issue by Lorenz1983** [cessda/cessda.cvs.two#902]
The "Filter per date" on the audit level does not work. Please check and rectify the error.

**Comment by pakoselo** [comment]
Everything worked, but the filtering is in descending mode, so the changes are at the end of the list. Another thing I notice that there are same audits repeated (after 30 records). Please see in dev: https://vocabularies-dev.cessda.eu/admin/audits?page=1&sort=auditEventDate,asc (i have used ascending sorting form the oldest to newest). In default, it filters last month. So I will be investigating the repetations of records.

**Comment by Lorenz1983** [comment]
Thanks for the info. Can the changes also be at the beginning of the list? And thanks for checking out the repetitions.

**Comment by pakoselo** [comment]
There is a sort on every field (except the extra data): Date, User and State. It can be asc or desc on any of them.
