### ISSUE TITLE
Change CC BY logo

### ISSUE THREAD

**Issue by Lorenz1983** [cessda/cessda.cvs.two#906]
Content:
Please change the CC BY logo on the website.

New logo: 
![image](https://github.com/cessda/cessda.cvs.two/assets/164059876/517de97f-4024-4474-84f2-9157eca68574)

Link:
https://vocabularies.cessda.eu/documentation/
https://vocabularies.cessda.eu/contentguide/

![image](https://github.com/cessda/cessda.cvs.two/assets/164059876/21cf2efe-b7b2-4840-85b5-8650d96b8df9)

![image](https://github.com/cessda/cessda.cvs.two/assets/164059876/95869ae6-270c-4e17-9f85-e273305454e8)

**Comment by pakoselo** [comment]
@Lorenz1983 content things should be probably assigned to @matthew-morris-cessda . We can't access (mostly) the static content as logos, images etc.

**Comment by Lorenz1983** [comment]
@pakoselo Thanks for the response and information. I will then assign the issue to Matthew.

**Comment by matthew-morris-cessda** [comment]
I'm unsure what changes you want, as the current logo is an official Creative Commons logo that represents this licence. Could you clarify?

**Comment by Lorenz1983** [comment]
In this logo, the male is not depicted.
